# =====================================================
# ? CONFIGURAÇÃO GERAL
# =====================================================
spring.application.name=kitanda_hospitalar_api
server.port=8081
#server.address=192.168.8.198

# =====================================================
# ? BANCO DE DADOS - POSTGRESQL 16
# =====================================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d3mfr3ripnbc73ao9ae0-a.oregon-postgres.render.com:5432/kitanda_hospitalar_db
spring.datasource.username=kitanda_hospitalar_db_user
spring.datasource.password=AfZuQ7oZGg5VdDrBkg8rtJ4sSSY2FxQx
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# =====================================================
# ? JWT (SEGURANÇA)
# =====================================================
jwt.secret=kS+Fc44ylUS9aiifSZI77tkwJASX6240bIH4ACTWL3w=

# =====================================================
# ? LOGGING
# =====================================================
logging.level.com.dvml.api.service=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =====================================================
# ? CONFIGURAÇÃO DE E-MAIL
# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dvml.comercial@gmail.com
spring.mail.password=emucpvuanmyngtul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =====================================================
# ? UPLOAD DE IMAGENS
# =====================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/produtos/
