# =====================================================
spring.application.name=api
server.port=8081

# =====================================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kitanda_hospitalar_db
spring.datasource.username=postgres
spring.datasource.password=DM.2026#321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =====================================================
jwt.secret=kS+Fc44ylUS9aiifSZI77tkwJASX6240bIH4ACTWL3w=
#oi
# =====================================================
# ? LOGGING
# =====================================================
logging.level.com.dvml.api.service=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dvml.comercial@gmail.com
spring.mail.password=emucpvuanmyngtul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


# =====================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/produtos/